import { rowsToCsv, downloadCsv } from "./csvTable";

// Column order mirrors the single-transaction form's 3 sections. Required
// columns must be present and non-blank; the rest fall back to sane
// defaults during processing (see bulkProcessing.js).
export const TEMPLATE_HEADERS = [
  "transaction_id",
  "customer_id",
  "account_id",
  "merchant_id",
  "device_id",
  "beneficiary_id",
  "amount",
  "currency",
  "country",
  "customer_home_country",
  "ip_country",
  "channel",
  "merchant_category",
  "transaction_time",
  "session_duration_seconds",
  "device_age_days",
  "account_age_days",
  "average_transaction_amount",
  "transactions_last_10_minutes",
  "failed_attempts_last_24_hours",
  "days_since_last_transaction",
  "merchant_risk_score",
  "customer_risk_score",
  "is_new_device",
  "is_new_beneficiary",
];

export const REQUIRED_HEADERS = [
  "customer_id",
  "merchant_id",
  "device_id",
  "amount",
  "currency",
  "country",
  "customer_home_country",
  "ip_country",
  "channel",
  "merchant_category",
  "device_age_days",
  "account_age_days",
  "average_transaction_amount",
];

const EXAMPLE_ROWS = [
  {
    transaction_id: "txn_100001",
    customer_id: "cust_501",
    account_id: "acc_901",
    merchant_id: "merchant_112",
    device_id: "device_82",
    beneficiary_id: "BEN_120",
    amount: "1250.00",
    currency: "SGD",
    country: "SG",
    customer_home_country: "SG",
    ip_country: "MY",
    channel: "mobile_app",
    merchant_category: "electronics",
    transaction_time: "2026-07-31T09:30:00Z",
    session_duration_seconds: "42",
    device_age_days: "5",
    account_age_days: "612",
    average_transaction_amount: "82.36",
    transactions_last_10_minutes: "1",
    failed_attempts_last_24_hours: "0",
    days_since_last_transaction: "2",
    merchant_risk_score: "24",
    customer_risk_score: "19",
    is_new_device: "true",
    is_new_beneficiary: "false",
  },
  {
    transaction_id: "txn_100002",
    customer_id: "cust_506",
    account_id: "",
    merchant_id: "merchant_150",
    device_id: "device_301",
    beneficiary_id: "",
    amount: "67.80",
    currency: "AUD",
    country: "AU",
    customer_home_country: "AU",
    ip_country: "AU",
    channel: "pos",
    merchant_category: "fuel",
    transaction_time: "2026-07-31T11:05:00Z",
    session_duration_seconds: "15",
    device_age_days: "540",
    account_age_days: "980",
    average_transaction_amount: "58.40",
    transactions_last_10_minutes: "0",
    failed_attempts_last_24_hours: "0",
    days_since_last_transaction: "1",
    merchant_risk_score: "10",
    customer_risk_score: "8",
    is_new_device: "false",
    is_new_beneficiary: "false",
  },
];

export function downloadBulkTemplate() {
  const csv = rowsToCsv(TEMPLATE_HEADERS, EXAMPLE_ROWS);
  downloadCsv("vaaligard-bulk-template.csv", csv);
}
